### PR TITLE
Rename several packages

### PR DESCRIPTION
**Pull request by dstallenberg**
core -> search
cfg-core -> cfg
base-testing-tool -> base-language 
plugin-core-graphing -> plugin-core-event-listener-graphing
plugin-core-metric-middleware-file-writer 
Plugin-core-sfuzz -> plugin-core-search-algorithm-sfuzz

Listener -> EventListener

Moved base-language to tools folder

### CODE REVIEW

**Comment by mitchellolsthoorn** [comment]
We should probably rename SFuzzPlugin to SFuzzSearchAlgorithmPlugin 
https://github.com/syntest-framework/syntest-core/blob/a8ef1d206f93428fa76ef1e39f052bd9e98dc7dc/plugins/plugin-core-search-algorithm-sfuzz/lib/SFuzzModule.ts#L33

**Comment by mitchellolsthoorn** [comment]
Even though `plugin-core-search-algorithm-sfuzz` contains multiple different kinds of plugins, the main type is `search-algorithm` so I think the naming makes sense. 

Modules can contain any type of extension we support, so we could rename our plugins to modules, but this would create more confusion. I suggest we keep the plugin naming as we can internally, just make sure that we keep tools and plugins separated.

**Comment by mitchellolsthoorn** [comment]
I would propose moving `cli` to tools. Even though it is not what we internally call a tool (an extension that functionality to our cli runner), it is more of a tool than a library. So, we can just say it is a special tool.

**Comment by dstallenberg** [comment]
> I would propose moving `cli` to tools. Even though it is not what we internally call a tool (an extension that functionality to our cli runner), it is more of a tool than a library. So, we can just say it is a special tool.

Fixed.

**Comment by dstallenberg** [comment]
> We should probably rename SFuzzPlugin to SFuzzSearchAlgorithmPlugin
> 
> https://github.com/syntest-framework/syntest-core/blob/a8ef1d206f93428fa76ef1e39f052bd9e98dc7dc/plugins/plugin-core-search-algorithm-sfuzz/lib/SFuzzModule.ts#L33

Fixed.

**Review by mitchellolsthoorn — APPROVED** [review]

**Pull request merged**
